# Generated by Django 5.1 on 2024-08-25 16:12

import datetime
import django.db.models.deletion
import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobNumber',
            fields=[
                ('invoice', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('created', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/designs')),
                ('description', models.CharField(max_length=50)),
                ('JobNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.jobnumber')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.today)),
                ('expiration', models.DateField(default=webapp.models.get_expiration)),
                ('JobNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.jobnumber')),
            ],
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.FileField(upload_to='files/proofs/')),
                ('approved', models.BooleanField(verbose_name=False)),
                ('description', models.CharField(max_length=300)),
                ('JobNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.jobnumber')),
            ],
        ),
    ]
